### ISSUE TITLE
meld 1.0.1 breaks supervisor 3.1.3

### ISSUE THREAD

**Issue by willejs** [Supervisor/meld3#21]
As soon as the release was cut, this broke supervisor for me.
```
Traceback (most recent call last):
  File "/usr/local/bin/supervisorctl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: meld3>=0.6.5
```

**Comment by mcdonc** [comment]
Errr. 1.0.1 is indeed > 0.6.5 so I'm not sure what's going on there.  This hasnt been reported elsewhere, and a fresh install on my system seems to work.

```
[chrism@thinkx projects]$ cd ~/tmp/
[chrism@thinkx tmp]$ virtualenv2.7 supertmp
New python executable in supertmp/bin/python
Installing setuptools, pip...done.
[chrism@thinkx tmp]$ cd supertmp/
[chrism@thinkx supertmp]$ bin/pip install supervisor
Downloading/unpacking supervisor
  Downloading supervisor-3.1.3.tar.gz (391kB): 391kB downloaded
  Running setup.py (path:/home/chrism/tmp/supertmp/build/supervisor/setup.py) egg_info for package supervisor
    
    warning: no previously-included files matching '*' found under directory 'docs/.build'
Downloading/unpacking meld3>=0.6.5 (from supervisor)
  Downloading meld3-1.0.1.tar.gz
  Running setup.py (path:/home/chrism/tmp/supertmp/build/meld3/setup.py) egg_info for package meld3
    
Installing collected packages: supervisor, meld3
  Running setup.py install for supervisor
    
    warning: no previously-included files matching '*' found under directory 'docs/.build'
    Skipping installation of /home/chrism/tmp/supertmp/lib/python2.7/site-packages/supervisor/__init__.py (namespace package)
    Installing /home/chrism/tmp/supertmp/lib/python2.7/site-packages/supervisor-3.1.3-py2.7-nspkg.pth
    Installing echo_supervisord_conf script to /home/chrism/tmp/supertmp/bin
    Installing pidproxy script to /home/chrism/tmp/supertmp/bin
    Installing supervisorctl script to /home/chrism/tmp/supertmp/bin
    Installing supervisord script to /home/chrism/tmp/supertmp/bin
  Running setup.py install for meld3
    
Successfully installed supervisor meld3
Cleaning up...
[chrism@thinkx supertmp]$ bin/echo_supervisord_conf > supervisord.conf
[chrism@thinkx supertmp]$ bin/supervisord -n -edebug
2015-03-31 16:13:18,728 INFO RPC interface 'supervisor' initialized
2015-03-31 16:13:18,728 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-03-31 16:13:18,729 INFO supervisord started with pid 4072
```

**Comment by willejs** [comment]
So, on an existing install 1.0.1 and 1.0.2 fail with that message, if i downgrade to 1.0.0 is the only version that works for me. On a new install 1.0.2 works fine however.

This is strange?

**Comment by mcdonc** [comment]
I cannot repeat it.  Can you tell us how to repeat the failure?

**Comment by willejs** [comment]
Im trying to figure it out.
the [diff](https://github.com/Supervisor/meld3/compare/1.0.0...1.0.1) looks like nothing really changes and meld doesent have any external third party dependencies?

**Comment by mnaberez** [comment]
1.0.1 contains a minor bug fix and is the first version to offer a universal wheel.  Your installation problems might be related to the wheel.  For reasons I don't know yet, `python setup.py sdist bdist_wheel upload` caused the 1.0.1 universal wheel package to be uploaded to PyPI as Py Version "2.7" instead of "py2.py3" like all the other universal wheels I have seen.  I removed the wheel from PyPI because I didn't want to chance this breaking installs until I figured it out.  I don't know why removing the wheel would cause the install to fail for you because I would think it would just choose the sdist, which was always present.  1.0.1 installed for me and Chris (shown above) from the sdist.

1.0.2 is a new version that has no code changes, just a new sdist and universal wheel.  The only difference was that I uploaded it with [twine](https://pypi.python.org/pypi/twine) instead, and PyPI now shows Py Version of the wheel as "py2.py3".  I spent some time trying to figure out what could cause this difference but came up empty handed.

Since the sdist and wheel for 1.0.2 look good now and you were able to install 1.0.2, I am going to close this issue.

**Comment by Ivoz** [comment]
@mnaberez AFAIK the "Py Version" mostly just relates to what version of python the package was created with. Which isn't necessarily relevant for users and not recorded at all for source distributions. Mostly a relic of a guess for relevant information that the cheeseshop needs. twine itself will upload a string which is in line with what pythons the package is designed to be used by, However it's not really used by pip for installation purposes anyway so despite looking like it needs to be something correct, is actually mostly irrelevant.

**Comment by jasimmk** [comment]
I am suffering with the same issue

```
root@consolidation1:/var/log# service supervisord start
Traceback (most recent call last):
  File "/usr/local/bin/supervisorctl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5
Traceback (most recent call last):
  File "/usr/local/bin/supervisorctl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: meld3>=0.6.5
could not start supervisord
root@consolidation1:/var/log# pip freeze|grep meld
meld3==1.0.2
```

**Comment by linuxr** [comment]
@jasimmk Thanks for your advice. I have also resolved this issue with "pip install distribute --upgrade".

**Comment by jaysh** [comment]
We just ran into this on a blank VM that is bootstrap via Ansible. Even with every requirement pinned, it still broke. We have to resort to 1.0.0 to workaround it.

**Comment by Ivoz** [comment]
@jaysh yeah, pinning distribute to a really old version will give you issues.

**Comment by jaysh** [comment]
@Ivoz I'm not following you. Pinning was how we worked around the issue - we weren't pinning *anything* up until it broke. Specifically, we were just doing `pip install supervisord` on a vanilla CentOS 6.x installation and taking the latest version. However, when this did break, we went back to the latest working production install, and ran `pip freeze`,  which picked had that version of distribute. From there, I just changed meld3 from 1.0.2 to 1.0.0.

What approach would you recommend we take?

**Comment by fcntl** [comment]
I have a crowbar. Now point me in the direction of the knees of the asshole who broke supervisor!!

**Comment by Ivoz** [comment]
@jaysh I'm guessing the initial installation failed since CentOS 6' setuptools package is also at a 6! year old version, [0.6.10](http://mirror.centos.org/centos/6/os/x86_64/Packages/python-setuptools-0.6.10-3.el6.noarch.rpm)

One method to resolving this would be to ensure you have latest system setuptools & pip before installing other stuff. Sometimes this can be a little hard if setuptools doesn't upgrade itself properly (reason for this to not just work was because of all the historical confusion / duplication between the setuptools & distribute projects). If it does work then you should be A-OK after.

Another would be to install the latest [virtualenv](https://virtualenv.pypa.io), which allows isolated python package environments. Then within an activate virtualenv that's been created, you can ensure you have latest versions of pip, setuptools and then supervisor (none of which will affect the system pip / setuptools).

A last option might be to use Armin Ronacher's [pipsi](https://github.com/mitsuhiko/pipsi), which is designed to install python-application/scripts inside their own virtualenvs for you automatically, and then only expose the final script to the system PATH.

**Comment by MJafarMashhadi** [comment]
@jasimmk 's workaround did the job. Thanks :)
