### ISSUE TITLE
The URL of xmlns definition does not reply

### ISSUE THREAD

**Issue by sblondon** [Supervisor/meld3#27]
The domain 'plope.com' does not reply so the example of html provides a link for the xml namespace which can not reply correctly:

```html
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:meld="http://www.plope.com/software/meld3"
      xmlns:bar="http://foo/bar">
```

This definition is used in Supervisor (in `ui/status.html` and `ui/tail.html`).

```
$ wget http://www.plope.com/software/meld3
--2019-07-25 17:51:10--  http://www.plope.com/software/meld3
Resolving www.plope.com (www.plope.com)... 64.34.174.146
Connecting to www.plope.com (www.plope.com)|64.34.174.146|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.
```

I don't know what is the best solution:
 - fix the webservice (if you can)? 
 - provide the xml file in the repository?
 - remove the xmlns definition in html example?

I can send an e-mail to the tech e-mail address provided by the `whois` if you want.

**Comment by mnaberez** [comment]
More information on namespace URLs:
https://stackoverflow.com/a/27614076

There is apparently no requirement that the URL be retrievable.  The [old URL](https://web.archive.org/web/20160401211813/http://plope.com/software/meld3/) never served anything other than the homepage for this project.  It doesn't seem like anything actually needs to be done here, but since the old URL has been down for several years now, it should probably be replaced with the URL for this repository.
